# Generated by Django 6.0.3 on 2026-03-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
