# Generated by Django 6.0.3 on 2026-03-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_original_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='original_filename',
            new_name='filename',
        ),
    ]
